#!/usr/bin/python3.8

from selenium import webdriver

chrome_path ="/root/chromedriver"

chromeOptions = webdriver.ChromeOptions()
chromeOptions.add_argument("--headless")
chromeOptions.add_argument("--remote-debugging-port=9222")
chromeOptions.add_argument('--no-sandbox')

driver = webdriver.Chrome(chrome_path,chrome_options=chromeOptions)

driver.get("http://vancouver.craigslist.com")
driver.find_element_by_xpath("""//*[@id="sss0"]/li[19]/a""").click()

posts = driver.find_elements_by_class_name("hdrlnk")
for post in posts:
        print(post.text)
